export type PropertyType = (
  | 'number'
  | 'url'
  | 'select'
  | 'multi_select'
  | 'status'
  | 'date'
  | 'email'
  | 'phone_number'
  | 'checkbox'
  | 'files'
  | 'created_by'
  | 'created_time'
  | 'last_edited_by'
  | 'last_edited_time'
  | 'formula'
  | 'title'
  | 'rich_text'
  | 'people'
  | 'relation'
  | 'rollup'
);
